[general]
show_welcome = false

[sys.files]
bootrom_path = 'C:\Users\Paul\Desktop\xbox_linux\Xbox-Emulator-Files\mcpx\mcpx_1.0.bin'
flashrom_path = 'C:\Users\Paul\Desktop\xbox_linux\artifacts\cromwell-hddfatx-autoboot-modernhdr-initrd32_1024.bin'
eeprom_path = 'C:\Users\Paul\Desktop\xbox_linux\run\eeprom.bin'
hdd_path = 'C:\Users\Paul\Desktop\xbox_linux\run\hdd\xbox_hdd_hddboot.raw'
dvd_path = 'C:\Users\Paul\Desktop\xbox_linux\artifacts\xromwell-modern-initrd32.iso'

[input.bindings]
port1 = 'keyboard'
port1_driver = 'usb-xbox-gamepad'
